name: Main CI Workflow

on:
  push:
  pull_request:

jobs:
  quality-check:
    uses: RomanDubrovin777/CI-forTest/.github/workflows/reusable-quality.yml@main
    with:
      python-version: '3.10'
      action: 'lint'

