name: CI
on:
  push:
  pull_request:
jobs:
  lint:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      python-version: '3.10'
      action: 'lint'

  test:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      python-version: '3.10'
      action: 'test'

