name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-python-3-10:
    name: Lint Python
    uses: ./.github/workflows/reusable-quality.yml  # תיקון: יש להוסיף את ./ לפני הנתיב
    with:
      python-version: '3.10'
      action: 'lint'

  test-python-3-9:
    name: Test Python
    uses: ./.github/workflows/reusable-quality.yml  # תיקון: יש להוסיף את ./ לפני הנתיב
    with:
      python-version: '3.9'
      action: 'test'

