name: Reusable Quality Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      action:
        required: true
        type: string

jobs:
  lint:
    if: ${{ inputs.action == 'lint' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8
        run: |
          flake8 src tests

  test:
    if: ${{ inputs.action == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          PYTHONPATH=src pytest
